1.What are data structures, and why are they important?
-> In Python, a data structure is a special way of organizing and storing data so it can be accessed and modified efficiently.
Python has built-in data structures like lists, tuples, dictionaries, and sets, and you can also build your own custom data structures using classes.

They ar important beacuse it provides structural way of storing data which makes code efficient to access and perform actions on data and many problem can be solved by picking right data structure and

2.Explain the difference between mutable and immutable data types with examples
->Mutable:-
     These can be changed after they are created.

      fruits = ["apple", "banana"]
      fruits.append("cherry")  # Modifies the list
      print(fruits)
  Immutable:-
     These cannot be changed after creation.
      
      # Creating a tuple
     coordinates = (10, 20)

      # Accessing elements
      print("X:", coordinates[0])  # Output: X: 10
      print("Y:", coordinates[1])  # Output: Y: 20

      # Tuples are immutable
      # coordinates[0] = 15  # ❌ This will raise a TypeError

  3.What are the main differences between lists and tuples in Python?
   ->
      List:-
        Lists are Mutable .These can be changed after they are created.

      fruits = ["apple", "banana"]
      fruits.append("cherry")  # Modifies the list
      print(fruits)

     Tuple:-

      Tuples ar Immutable. These cannot be changed after creation.
      
      # Creating a tuple
     coordinates = (10, 20)

      # Accessing elements
      print("X:", coordinates[0])  # Output: X: 10
      print("Y:", coordinates[1])  # Output: Y: 20

      # Tuples are immutable
      # coordinates[0] = 15  # ❌ This will raise a TypeError

  4.Describe how dictionaries store data?
  ->
     A dictionary in Python is a collection of key-value pairs.
      Each key maps to a specific value, and you can use the key to quickly access or update the value.

      Key → Value
       
      student = {
      "name": "Alice",
      "age": 20,
      "major": "Computer Science"
      }
      print(student["name"])  # Output: Alice

  5.Why might you use a set instead of a list in Python?
   ->1.Sets automatically remove duplicates
     2.Sets use a hash table under the hood, so checking if an item exists is much faster than in a list.

     If your use case doesn't require duplicates or ordering, sets make your intention more clear.
  6.What is a string in Python, and how is it different from a list?
     -> A string in Python is a sequence of characters enclosed in quotes.
        ex:-name = "Alice"
        Differences:-
        1.Strings are immutable, which means once you create them, you can’t change their characters individually unlike list.
        2.	String isSequence of characters .List	Sequence of any type of items
        3.String	Enclosed in quotes	.List Enclosed in square brackets
  7.How do tuples ensure data integrity in Python?

   -> Data integrity means that the data stays accurate, consistent, and
      unchanged unless intentionally modified.
      Tuples in Python are immutable, meaning:

      You cannot change, add, or remove elements once the tuple is created.

      This immutability helps protect the data from accidental modification
  8.What is a hash table, and how does it relate to dictionaries in Python?
     ->  A hash table is a data structure that stores data in key-value pairs,
       using a hash function to compute an index (or location) where the value is stored.

       In Python, the dict (dictionary) is implemented using a hash table.Its is also works with key value pair like hash table.
  9. Can lists contain different data types in Python?
   ->Yes, lists in Python can contain different data types.

     my_list = [1, "hello", 3.14, True, [2, 3], {"key": "value"}]
     print(my_list)

  10. Explain why strings are immutable in Python?
     ->Strings are immutable in Python because once a string is created, its contents cannot be changed. If you try to modify a string, Python creates a new string instead of changing the original one

     1.Efficiency and Memory Optimization.Python often reuses string objects with the same value.
     2.Since strings cannot be changed, they are safe to use in multi-threaded programs without worrying about accidental changes

  11. What advantages do dictionaries offer over lists for certain tasks?

       ->Dictionaries: Retrieve values by keys instantly.

         Lists: Require searching through the list

        1. Accessing values would be faster in dict compar to list
        2. dictionary Does not allows duplicate key values  unlike list
        3.dictionary had key value pair structure list doesn't had that

   12.Describe a scenario where using a tuple would be preferable over a list?
     -> If we want data to be constant and not to be change accidentally than tuple is more preferable than list
     ex. like dictionary keys

   13 .How do sets handle duplicate values in Python?
     ->Sets in Python are implemented using hash tables, just like dictionary keys.When you try to add a duplicate, the set detects that the value already exists and skips it.

   14. How does the “in” keyword work differently for lists and dictionaries?
     -> For Lists:
             in checks if a value exists as an element in the list.
        For Dictionaries:
             in checks if a key exists in the dictionary, not the values.

   15.Can you modify the elements of a tuple? Explain why or why not
      -> No we can not modify elements of tuple because tuple is immutable it could not be modified.once a tuple is created, its elements cannot be changed, added, or removed.

   16.What is a nested dictionary, and give an example of its use case?
      ->A nested dictionary in Python is a dictionary within a dictionary.
         ex.student_info = {
         "Alice": {
                "age": 20,
                "major": "Computer Science",
                "courses": ["CS101", "MATH201"]
                },
        "Bob": {
            "age": 22,
            "major": "Physics",
            "courses": ["PHYS101", "CS101"]
        }
      }
      The main dictionary has keys "Alice" and "Bob".

      The value associated with each key is another dictionary that contains information about the student (age, major, courses).

  17.Describe the time complexity of accessing elements in a dictionary?
     ->In Python, dictionaries are implemented using hash tables, which allow
       for efficient access to elements.
        Average Case: O(1):=In most cases, accessing an element by its key in a dictionary is constant time, i.e., O(1). This means the time it takes to access a value does not depend on the size of the dictionary
        
        Worst Case: O(n):=In rare cases, when there are many collisions (two or more keys having the same hash), the dictionary may fall back to linear search to resolve these collisions, resulting in O(n) time complexity.
        
  18.In what situations are lists preferred over dictionaries?
     ->Lists are preferred over dictionaries when you need an ordered collection, indexed access, duplicates, or need to perform sorting and slicing.

  19. Why are dictionaries considered unordered, and how does that affect data retrieval?
     ->Dictionaries are considered unordered because they store data in a hash table, and this affects data retrieval by allowing fast access via keys but not by order.

  20.Explain the difference between a list and a dictionary in terms of data retrieval.
     ->List: Data is retrieved by index (position), meaning you access elements in a specific order.

      Dictionary: Data is retrieved by key, allowing fast lookups but with no inherent order.

      Performance: Lists require sequential searching (O(n)) for non-indexed access, while dictionaries offer constant time lookup (O(1)) for key-based access.

PRACTICAL QUESTIONS

1.Write a code to create a string with your name and print it?

In [ ]:
name="Ravi Chandra"
print(name)

Ravi Chandra

2 Write a code to find the length of the string "Hello World"?

In [ ]:
string= "Hello World"
print(len(string))

11

3.Write a code to slice the first 3 characters from the string "Python Programming"?

In [ ]:
string="Python Programming"
print(string[0:3])

Pyt

4.Write a code to convert the string "hello" to uppercase?

In [ ]:
string="hello"
print(string.upper())

HELLO

5.Write a code to replace the word "apple" with "orange" in the string "I like apple"?

In [ ]:
string="I like apple"
new_string=string.replace("apple","orange")
print(new_string)

I like orange

6. Write a code to create a list with numbers 1 to 5 and print it?

In [ ]:
numbers = [1, 2, 3, 4, 5]
print(numbers)

[1, 2, 3, 4, 5]

7. Write a code to append the number 10 to the list [1, 2, 3, 4]?

In [ ]:
numbers_list=[1,2,3,4]
print(numbers_list)
numbers_list.append(10)
print(numbers_list)

[1, 2, 3, 4]
[1, 2, 3, 4, 10]

8.Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]?

In [ ]:
num_list=[1, 2, 3, 4, 5]
print(num_list)
num_list.remove(3)
print(num_list)

[1, 2, 3, 4, 5]
[1, 2, 4, 5]

9.Write a code to access the second element in the list ['a', 'b', 'c', 'd']?

In [ ]:
list1=['a', 'b', 'c', 'd']
print(list1[1])

b

10.Write a code to reverse the list [10, 20, 30, 40, 50]?

In [ ]:
list2= [10, 20, 30, 40, 50]
list2.reverse()
print(list2)

[50, 40, 30, 20, 10]

11.Write a code to create a tuple with the elements 100, 200, 300 and print it?

In [ ]:
tuple1=tuple([100,200,300])
print(tuple1)

(100, 200, 300)

12. Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')?

In [ ]:
tuple2=tuple(['red', 'green', 'blue', 'yellow'])
print(tuple2[-2])

blue

13.Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [ ]:
tuple3=(10,20,5,15)
print(min(tuple3))

5

14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')?

In [ ]:
tuple4=('dog', 'cat', 'rabbit')
print(tuple4.index('cat'))

1

15.Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [ ]:
fruits = ("apple", "banana", "mango","kiwi")

if "kiwi" in fruits:
    print("Kiwi is in the tuple.")
else:
    print("Kiwi is not in the tuple.")

Kiwi is in the tuple.

16.Write a code to create a set with the elements 'a', 'b', 'c' and print it?

In [ ]:
set1=set(['a','b','c'])
print(set1)

{'a', 'b', 'c'}

17. Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

In [ ]:
set2={1,2,3,4,5}
print(set2)
set2.clear()
print(set2)

{1, 2, 3, 4, 5}
set()

18. Write a code to remove the element 4 from the set {1, 2, 3, 4}.

In [ ]:
my_set = {1, 2, 3, 4}
my_set.remove(4)
print(my_set)

{1, 2, 3}

19. Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5}

20. Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

In [ ]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}
intersection_set = set1.intersection(set2)
print(intersection_set)

{2, 3}

21. Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

In [ ]:
my_dict={"name":"ravi","age":23,"city":"mumbai"}
print(my_dict)

{'name': 'ravi', 'age': 23, 'city': 'mumbai'}

22. Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

In [ ]:
person = {'name': 'John', 'age': 25}
person['country'] = 'USA'
print(person)

{'name': 'John', 'age': 25, 'country': 'USA'}

23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [ ]:
my_dict1= {'name': 'Alice', 'age': 30}
print(my_dict1['name'])

Alice

24. Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

---

In [ ]:
my_dict3= {'name': 'Bob', 'age': 22, 'city': 'New York'}
my_dict3.pop('age')
print(my_dict3)

{'name': 'Bob', 'city': 'New York'}

25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

In [ ]:
my_dict4= {'name': 'Alice', 'city': 'Paris'}
if 'City' in my_dict4:
    print(True)
else:
  print(False)

False

26. Write a code to create a list, a tuple, and a dictionary, and print them all.

In [15]:
my_list = [1, 2, 3]
my_tuple = ('a', 'b', 'c')
my_dict = {'name': 'Alice', 'age': 30}

print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3]
Tuple: ('a', 'b', 'c')
Dictionary: {'name': 'Alice', 'age': 30}

27. Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)

In [16]:
import random

random_numbers = random.sample(range(1, 101), 5)

random_numbers.sort()

print("Sorted random numbers:", random_numbers)

Sorted random numbers: [25, 32, 53, 70, 86]

28. Write a code to create a list with strings and print the element at the third index.

In [18]:
my_list = ["apple", "banana", "cherry", "date", "fig"]
print(my_list[3])

date

29. Write a code to combine two dictionaries into one and print the result.

In [21]:
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

dict1.update(dict2)
print(dict1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

30. Write a code to convert a list of strings into a set.

In [22]:
my_list = ["apple", "banana", "cherry", "apple"]
my_set = set(my_list)
print(my_set)

{'cherry', 'apple', 'banana'}